### ISSUE TITLE
Error: Couldn't find package "@waves/money-like-to-node@0.0.6"

### ISSUE THREAD

**Issue by pitersky** [wavesplatform/waves-signature-adapter#42]
Hello. Updated waves-signature-adapter to 5.0.0-a7 and got this error. 

I am executing ```yarn```

```
error Couldn't find package "@waves/money-like-to-node@0.0.6" required by "@waves/signature-adapter@5.0.0-a7" on the "npm" registry.
```
@waves/money-like-to-node@0.0.6 seems to be not published in npm

Thank you.

**Comment by dractw** [comment]
Same issue with  `@waves/money-like-to-node@0.0.7` facing both `yarn` and `npm`

**Comment by tsigel** [comment]
@pitersky, do not use alpha packages.

**Comment by tsigel** [comment]
@dractw @waves/money-like-to-node - is private package without docs only for core of waves adapter.

**Comment by dractw** [comment]
@tsigel but if I try to install any another version of `@waves/signature-adapter` such as `5.0.2`  or `5.0.1` this error message appears with different versions of `money-like-to-node`, but as we find out - it shouldn't.

**Comment by pitersky** [comment]
Works fine with 4.5.4. Thank you.
