### ISSUE TITLE
If possible to get seed phrase using waves-signature-adapter ?

### ISSUE THREAD

**Issue by narmathamuthu** [wavesplatform/waves-signature-adapter#59]
Hi team , 

If possible to get seed phrase using address or private key or public key ?

Please share the syntax ASAP. 

I am struggling on this. 

Kindly provide the solution ASAP.

**Comment by tsigel** [comment]
Hi! Create seed phrase from address or key pair is impossible.
But u can create any transactions and login in wallet with u private key. 
Cheers!

**Comment by narmathamuthu** [comment]
@tsigel  Okay fine.

Can you please share the syntax for  transactions with login wallet.

**Comment by tsigel** [comment]
For sign transaction:

```typescript
import { transfer } from '@waves/waves-transactions';

transfer({ amount: 100, recipient: 'WAVES_ADDRESS' }, { privateKey: 'PRIVATE_KEY' })
```

In wallet: https://dex.wavesplatform.com/import/restore
![Снимок экрана 2019-11-16 в 14 07 31](https://user-images.githubusercontent.com/3913017/68992315-c1486180-087a-11ea-82b4-e698ba61099e.png)

**Comment by narmathamuthu** [comment]
@tsigel  

Okay thank you !!!

Please see the below syntax: 

Syntax 1 : 

**Request :** 

const signedTranserTx = transfer(
  {
    assetId: 'WAVES',
    amount: Math.pow(10, 8) * 0.1,
    feeAssetId: 'WAVES',
    recipient: "XXX", 
    fee : Math.pow(10, 8) * 0.005,
    timestamp: Date.now()
  },{ privateKey: 'XXXX' });

  const nodeUrl = "https://testnodes.wavesnodes.com";

  broadcast({ ...signedTranserTx, chainId: "T" }, nodeUrl)
  .then(resp => console.log(resp))
  .catch(err => console.error(err));

**Response :** 

![image](https://user-images.githubusercontent.com/55826071/68992451-a6351c00-0891-11ea-81cc-ea56443f28b1.png)

Syntax 2 : 

**Request :** 

const signedTranserTx = transfer(
  {
    assetId: 'WAVES',
    senderPublicKey:'XXXX',
    amount: Math.pow(10, 8) * 0.1,
    feeAssetId: 'WAVES',
    recipient: "XXXX", 
    fee : Math.pow(10, 8) * 0.005,
    timestamp: Date.now()
  },{ privateKey: 'XXXX' });

  const nodeUrl = "https://testnodes.wavesnodes.com";

  broadcast({ ...signedTranserTx, chainId: "T" }, nodeUrl)
  .then(resp => console.log(resp))
  .catch(err => console.error(err));

**Response :** 

![image](https://user-images.githubusercontent.com/55826071/68992479-04fa9580-0892-11ea-93dd-7da3ed7b2b9a.png)

Kindly check and tell what i am wrong.

**Comment by siemarell** [comment]
Good day. I cant get why you are getting this errors.
Try this code. I surely works, I've just checked. And make sure you have latest version of waves-transactions library (3.24.0) 
```javascript
const wt = require('@waves/waves-transactions');

const secretKey = 'HjdUN7kPLevEAkFSQgwEBXyupoBAFkRRTDYYDmk3mnhE';
const tx = wt.transfer({
        amount: 10000000,
        recipient: '3N2eocVyBbeMNixumkD3MbUUe4MJp5zmWPu'
    },
    {privateKey: secretKey});
const nodeUrl = 'https://testnodes.wavesnodes.com';
wt.broadcast(tx, nodeUrl);
```
